### ISSUE TITLE
`controlled_frame` vs `tcp_frame`?

### ISSUE THREAD

**Issue by gavanderhoorn** [UniversalRobots/Universal_Robots_ROS_cartesian_control_msgs#6]
Looking at the message definition(s) a bit closer, it appears `CartesianTrajectory` has a `controlled_frame`:

https://github.com/UniversalRobots/Universal_Robots_ROS_cartesian_control_msgs/blob/efd9900092aaa2ce030790138ee870a8b5d6a85a/msg/CartesianTrajectory.msg#L4

 while the feedback section of `FollowCartesianTrajectory` defines a `tcp_frame`:

https://github.com/UniversalRobots/Universal_Robots_ROS_cartesian_control_msgs/blob/efd9900092aaa2ce030790138ee870a8b5d6a85a/action/FollowCartesianTrajectory.action#L22

IIRC these refer to the same entity, so I'm wondering whether `tcp_frame` is a remnant from before we renamed the field to `controlled_frame` or there is some other rationale.

**Comment by gavanderhoorn** [comment]
FYI: @dave992

**Comment by gavanderhoorn** [comment]
@fmauch: any idea?

**Comment by fmauch** [comment]
Looking back at the [design document](https://fzi-robot-interface-proposal.readthedocs.io/en/latest/proposal/index.html#cartesiantrajectoryaction) it seams that we indeed missed to rename that.

**Comment by gavanderhoorn** [comment]
With #7 (and #8) merged, I'll close this.

thanks @fmauch.
